name: CI

on:
  pull_request:
    branches: [ master ]

  push:

jobs:
  test-c:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      run: |
        uv pip install --system --upgrade setuptools wheel

    - name: Install package
      run: |
        uv pip install --system .

    - name: Install Debian dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y opencl-headers nvidia-cuda-dev nvidia-opencl-dev oclgrind

    - name: Install Futhark
      run: |
          wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
          tar xf futhark-nightly-linux-x86_64.tar.xz
          (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)
          echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Run tests (C backend)
      run: |
        futhark c --library test.fut
        futhark c --library test_badconsts.fut
        build_futhark_ffi test
        build_futhark_ffi test_badconsts
        python test.py

    - name: Run tests (multicore backend)
      run: |
        futhark multicore --library test.fut
        futhark multicore --library test_badconsts.fut
        build_futhark_ffi test
        build_futhark_ffi test_badconsts
        python test.py

    - name: Run tests (OpenCL backend)
      run: |
        futhark opencl --library test.fut
        futhark opencl --library test_badconsts.fut
        build_futhark_ffi test
        build_futhark_ffi test_badconsts
        oclgrind python test.py

    - name: Run tests (CUDA backend)
      run: |
        futhark cuda --library test.fut
        futhark cuda --library test_badconsts.fut
        build_futhark_ffi test
        build_futhark_ffi test_badconsts
        # Can't actually run them without a CUDA device...
